### ISSUE TITLE
veramo-v5 version

### ISSUE THREAD

**Issue by sanderPostma** [uport-project/veramo-plugin#24]
I'd like to see a branch that is compatible with Veramo v5. I've made some attempts, but I am struggling with the imports when resolved by ts-jest. Keeps throwing
`Test suite failed to run

    Cannot find module '@veramo/cli/build/setup' from 'packages/connection-manager/__tests__/localAgent.test.ts'

      at Resolver._throwModNotFoundError (node_modules/.pnpm/jest-resolve@29.4.3/node_modules/jest-resolve/build/resolver.js:427:11)
`

**Comment by nickreynolds** [comment]
@sanderPostma you are absolutely correct, and I want to apologize for not having this already! We should have taken care of this simultaneously with the v5 release, but it slipped through the cracks. The upgrade should be relatively straightforward, and we will try to take care of it as quickly as possible
